name: Android CI

on:
  push:
    branches:
      - gamehub-608-build
  pull_request:
    branches:
      - gamehub-608-build

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ secrets.GITHUB_PACKAGES_USERNAME }}
      ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ secrets.GITHUB_PACKAGES_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
